variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script: 
   - "git submodule add --force https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.univ-artois.fr/lanceurrayons/testslanceurrayons.git tests"
   - "git submodule update --remote --init"

stages:
  - build
  - initial
  - basic
  - realist
  - matrices
  - efficiency
  - qa
  - mystery


auditcode:
   stage: qa
   script: "sonar-scanner -Dsonar.login=$SONARTOKEN -Dsonar.projectKey=tracer$CI_PROJECT_ID -Dsonar.projectName=Raytracer_by_$CI_PROJECT_NAMESPACE"
   tags:
     - shell
     - sonar
   
executable:
   stage: build
   script: "./build.sh"
   artifacts:
      paths: 
      - raytracer.jar
      - bin
      - "*.sh"
   tags:
     - shell
