variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script: 
   - "git submodule add --force https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.univ-artois.fr/lanceurrayons/testslanceurrayons.git tests"
   - "git submodule update --remote --init"
   - "cd tests"
   - "git checkout $CI_COMMIT_REF_NAME"
   - "cd .."

stages:
  - build
  - tools
  - basic
  - top
  - extra
  - qa

comparateur:
   stage: tools
   script: "cd tests; ./tests1.sh"
   tags: 
     - shell

vectests:
   stage: tools
   script: "cd tests; ./tests2.sh"
   tags: 
     - shell

lecturescenes:
   stage: basic
   script: "cd tests; ./tests3.sh"
   tags: 
     - shell

premieresimages:
   stage: basic
   script: "cd tests; ./tests4.sh"
   tags:
     - shell

imagescouleur:
   stage: basic
   script: "cd tests; ./tests5.sh"
   tags:
     - shell

plansettriangles:
   stage: basic
   script: "cd tests; ./tests6.sh"
   tags:
     - shell

lumiereindirecte:
   stage: top
   script: "cd tests; ./tests7.sh"
   tags:
     - shell

imagesmystere:
   stage: top
   script: "cd tests; ./mysteres.sh"
   tags:
     - shell

transformations1:
   stage: extra
   script: "cd tests; ./tests8.sh"
   tags:
     - shell
   only:
     - transformations

transformations2:
   stage: extra
   script: "cd tests; ./tests9.sh"
   tags:
     - shell
   only:
     - transformations

transformations3:
   stage: extra
   script: "cd tests; ./tests11.sh"
   tags:
     - shell
   only:
     - transformations

damiers:
   stage: top
   script: "cd tests; ./tests10.sh"
   tags:
     - shell

auditcode:
   stage: qa
   script: "./build.sh ; sonar-scanner -Dsonar.login=$SONARTOKEN -Dsonar.projectKey=tracer$CI_PROJECT_ID -Dsonar.projectName=Raytracer_by_$CI_PROJECT_NAMESPACE"
   tags:
     - shell
     - sonar
   
executable:
   stage: build
   script: "./build.sh"
   artifacts:
      paths: 
      - raytracer.jar
      - "*.sh"
   tags:
     - shell

anticrenelage:
   stage: top
   script: "cd tests; ./tests12.sh"
   tags:
     - shell
