variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROXY: "-Dhttp.proxyHost=cache-etu.univ-artois.fr -Dhttp.proxyPort=3128 -Dhttps.proxyHost=cache-etu.univ-artois.fr -Dhttps.proxyPort=3128 -Dhttp.nonProxyHosts=localhost"
  SONARINFO: "-Dsonar.host.url=http://sonarqube.univ-artois.fr/ -Dsonar.login=$SONARTOKEN -Dsonar.projectKey=tracer$CI_PROJECT_ID -Dsonar.projectName=Raytracer_by_$CI_PROJECT_NAMESPACE"


default:
  image: cache-ili.univ-artois.fr/proxy_cache/library/gradle:7.6-jdk11
  tags: 
     - docker

before_script: 
  - "git submodule add --force https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.univ-artois.fr/lanceurrayons/testslanceurrayons.git tests"
  - "git submodule update --remote --init"

stages:
  - build
  - initial
  - basic
  - realist
  - matrices
  - efficiency
  - qa
  - mystery

   
executable:
  stage: build
  script: "./build.sh"
  artifacts:
    paths: 
      - raytracer.jar
      - bin
      - "*.sh"